# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-14 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beverages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('Description', models.TextField(blank=True)),
                ('Availability', models.BooleanField(default=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='SellingItems/Beverages/')),
            ],
        ),
        migrations.CreateModel(
            name='EdibleItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('Description', models.TextField(blank=True)),
                ('Availability', models.BooleanField(default=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='SellingItems/EdibleItems/')),
            ],
        ),
        migrations.CreateModel(
            name='PackedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('Description', models.TextField(blank=True)),
                ('Availability', models.BooleanField(default=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='SellingItems/Beverages/')),
            ],
        ),
    ]
