# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-14 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SellingItems', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Beverages',
            new_name='Beverage',
        ),
        migrations.RenameModel(
            old_name='EdibleItems',
            new_name='EdibleItem',
        ),
        migrations.RenameModel(
            old_name='PackedItems',
            new_name='PackedItem',
        ),
    ]
