# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-14 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellingItems', '0002_auto_20170914_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packeditem',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='SellingItems/PackedItems/'),
        ),
    ]
