# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-14 15:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mobileNumber', models.IntegerField(default=0)),
                ('isFaculty', models.BooleanField(default=False)),
                ('avatar', models.ImageField(default='/static/User/defaultProfileImage.png', upload_to='User/')),
            ],
        ),
    ]
